version: '3.8'

services:
  backend:
    build: 
      context: ./adrift
      dockerfile: Dockerfile.prod
    command: gunicorn adrift.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/adrift/backend/staticfiles
      - media_volume:/home/adrift/backend/mediafiles
      - ./adrift/logs/:/home/adrift/backend/logs/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/adrift/backend/staticfiles
      - media_volume:/home/adrift/backend/mediafiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: