# Generated by Django 5.0.6 on 2024-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPER', 'Developer')], max_length=30, unique=True),
        ),
    ]
